# Première pipeline
#Nom de la pipeline
name: Pipeline démo

# L'event qui doit déclencher la pipeline
on: [push]

# Liste des actions qui s'exécutent lors du trigger
jobs:
  #nom du job
  first-job:
    # sur quoi le job est executé
    runs-on: ubuntu-latest
    #les étapes du process du job
    steps:
      - name: Test de mon premier job
        run: echo "Ceci est mon premier job"
